before:
  hooks:
    - go mod download
builds:
- env:
  - CGO_ENABLED=0
nfpms:
  - id: packages # here we say that artifacts built with nfpm will be identified with `packages` string.
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brews:
  - tap:
      owner: elwin
      name: homebrew-tools

    commit_author:
      name: elwin
      email: elwin.stephan@gmail.com

    url_template: "https://github.com/elwin/table/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    homepage: "https://github.com/elwin/table"
    description: "Print CSV and JSON documents in a table format."
snapcrafts:
  -
    summary: Table
    description: "Print CSV and JSON documents in a table format."
    publish: true
    license: MIT
publishers:
  - name: fury.io
    # by specifying `packages` id here goreleaser will only use this publisher
    # with artifacts identified by this id
    ids:
      - packages
    dir: "{{ dir .ArtifactPath }}"
    cmd: curl -F package=@{{ .ArtifactName }} https://{{ .Env.FURY_TOKEN }}@push.fury.io/netdevops/

